name: Build POPFile Image

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code ophalen
        uses: actions/checkout@v5

      - name: Build docker image
        run: |
          docker build -t mijn-popfile-test .
          echo "Build completed."
